### ISSUE TITLE
SteamVR 2.x

### ISSUE THREAD

**Issue by VizRCA** [googlevr/tilt-brush-toolkit#28] opened 2019-01-21 15:37 UTC
The current version of SteamVR (2.x.x) available on the Unity asset store is not compatible with v16 release of tiltbrush toolkit

**Comment by bddckr** [comment] 2019-01-22 07:52
If anyone does any work in this direction I suggest to not target the mentioned Asset Store release until it is on 2.2 of the plugin. There will be breaking changes and enough things changed to not make it worthwhile.

The latest version (and betas) can be found on the GitHub repo at [ValveSoftware/steamvr_unity_plugin](https://github.com/ValveSoftware/steamvr_unity_plugin/releases).

**Comment by HelloOrwell** [comment] 2019-01-22 14:19
Glad to see this confirmed. I thought it was something I had messed up in my process.

**Comment by dubois** [comment] 2019-06-24 16:54
Almost certainly the same issue as https://github.com/googlevr/tilt-brush-toolkit/issues/34, so closing this as duplicate because that has the best information.

**Closed by dubois** 2019-06-24 16:54 UTC
